######################################################################
# Automatically generated by qmake (3.0) ?? 6? 21 16:36:26 2017
######################################################################

TEMPLATE = app
TARGET = qmake
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += widgets gui
